# Generated by Django 5.0.7 on 2024-07-31 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0007_subscription"),
        ("users", "0006_payments_pay_link_payments_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="paid_lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="lms.lesson",
                verbose_name="Оплаченный урок",
            ),
        ),
    ]
