# Generated by Django 5.0.7 on 2024-07-31 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_payments_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="pay_link",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Ссылка на оплату"
            ),
        ),
    ]
