# Generated by Django 5.0.7 on 2024-07-17 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"verbose_name": "Курс", "verbose_name_plural": "Курсы"},
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={"verbose_name": "Урок", "verbose_name_plural": "Уроки"},
        ),
        migrations.RemoveField(
            model_name="course",
            name="lesson",
        ),
        migrations.AddField(
            model_name="lesson",
            name="courses",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="lms.course",
                verbose_name="курс",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="link_video",
            field=models.URLField(max_length=150, verbose_name="название"),
        ),
    ]
