# Generated by Django 5.0.7 on 2024-07-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0004_course_owner_lesson_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="title",
            field=models.CharField(
                blank=True, max_length=25, null=True, verbose_name="название"
            ),
        ),
    ]
